---
AllCops:
  TargetRubyVersion: 2.7

Layout/LineLength:
  Max: 120
  Exclude:
    - 'cookbooks/*/test/fixtures/**/*'
    - 'cookbooks/*/test/integration/**/*'
    - 'cookbooks/*/spec/**/*'

Metrics/BlockLength:
  CountComments: false  # count full line comments?
  Max: 25
  Exclude:
    - 'cookbooks/*/test/fixtures/**/*'
    - 'cookbooks/*/test/integration/**/*'
    - 'cookbooks/*/spec/**/*'
